name: todos
description: A new Flutter project.
publish_to: "none"

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"


dependencies:
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  hooks_riverpod:
  path_provider: ^2.1.5
  riverpod:
  uuid: ^4.0.0

dev_dependencies:
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  drift_dev: ^2.28.3
  flutter_test:
    sdk: flutter
  riverpod_lint:

flutter:
  uses-material-design: true
